apiVersion: v1
kind: Service
metadata:
  name: product-app
spec:
  selector:
    app: product-app
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
      nodePort: 30010
  type: NodePort
